/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatsWindow.java
 *
 * Created on Feb 5, 2011, 3:01:09 PM
 */

package org.ingatan.component;

import org.ingatan.ThemeConstants;
import org.ingatan.component.librarymanager.MultipleLibrarySelector;

/**
 *
 * @author thomas
 */
public class StatsWindow extends javax.swing.JFrame {

    /** Creates new form StatsWindow */
    public StatsWindow() {
        initComponents();
        contentPane.add(new LibraryStatsGraphPane());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        horiz = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnQuizHistory = new javax.swing.JButton();
        btnLibraryGraphs = new javax.swing.JButton();
        btnGroupGraphs = new javax.swing.JButton();
        btnRewards = new javax.swing.JButton();
        contentPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        lblHeading.setText("Statistics and History");
        lblHeading.setFont(ThemeConstants.hugeFont.deriveFont(26.0f));
        lblHeading.setForeground(ThemeConstants.textColour);
        getContentPane().add(lblHeading);

        horiz.setBackground(new java.awt.Color(254, 254, 185));
        horiz.setAlignmentX(0.0F);
        horiz.setLayout(new javax.swing.BoxLayout(horiz, javax.swing.BoxLayout.LINE_AXIS));

        menuPanel.setBackground(new java.awt.Color(217, 228, 239));
        menuPanel.setAlignmentY(0.05F);
        menuPanel.setMaximumSize(new java.awt.Dimension(100, 150));
        menuPanel.setPreferredSize(new java.awt.Dimension(150, 450));
        menuPanel.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        btnQuizHistory.setText("Quiz History");
        menuPanel.add(btnQuizHistory);

        btnLibraryGraphs.setText("Library Graphs");
        btnLibraryGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryGraphsActionPerformed(evt);
            }
        });
        menuPanel.add(btnLibraryGraphs);

        btnGroupGraphs.setText("Group Graphs");
        menuPanel.add(btnGroupGraphs);

        btnRewards.setText("Rewards");
        menuPanel.add(btnRewards);

        horiz.add(menuPanel);

        contentPane.setBackground(new java.awt.Color(197, 213, 223));

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        horiz.add(contentPane);

        getContentPane().add(horiz);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLibraryGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryGraphsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibraryGraphsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGroupGraphs;
    private javax.swing.JButton btnLibraryGraphs;
    private javax.swing.JButton btnQuizHistory;
    private javax.swing.JButton btnRewards;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel horiz;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables

}
